name: Caching and Artifacts
on: [workflow_dispatch]

jobs:
  cache-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache go modules
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: ~/go
          key: ${{ runner.os }}-go-cache-${{ hashFiles('./go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-cache-
      - name: Display Cache Output
        run: echo "${{ toJson(steps.cache-dependencies.outputs) }}"
      - name: Install dependencies
        run: time go mod tidy
      - name: Run Tests
        run: make test-coverage
      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          path: coverage
          name: test-coverage
          retention-days: 10
  download-artifacts:
    runs-on: ubuntu-latest
    needs: cache-deps
    steps:
      - name: Download Code Coverage
        uses: actions/download-artifact@v4
        with:
          name: test-coverage
          path: code-coverage-report
      - run: ls -a
        working-directory: code-coverage-report
      - run: cat coverage.out
        working-directory: code-coverage-report
