name: Caching and Artifacts
on: [workflow_dispatch]

jobs:
  cache-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache go modules
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: ~/go
          key: "go-cache"
      - name: Display Cache Output
        run: echo "${{ toJson(steps.cache-dependencies.outputs) }}"
      - name: Install dependencies
        run: time go mod tidy