name: Checkout
on: [push]

jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -a
      - name: Checkout
        run: |
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
      - name: List Files After
        run: ls -a