name: Dynamic Matrix
on:
  workflow_dispatch:
    inputs:
      os:
        description: Operating Systems
        default: "windows-latest,ubuntu-latest"
        type: string

jobs:
  setup-go:
    strategy:
      fail-fast: true
      matrix:
        os: ${{ toJson(format('[{0}]', inputs.os)) }}
        go-version: ['1.20', '1.21', '1.22']
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version