name: Dynamic Matrix
on:
  workflow_dispatch:
    inputs:
      os:
        description: Operating Systems
        default: "windows-latest,ubuntu-latest"
        type: string
      go-version:
        description: Go Version
        default: "1.20,1.21,1.22"
        type: string

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix-arrays: ${{ steps.matrix-arrays.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        id: matrix-arrays
        with:
          script: "return {os: context.payload.inputs['os'].split(','),
            'go-version': context.payload.inputs['go-version'].split(',')}"
          result-encoding: json
      - run: echo ${{ steps.matrix-arrays.outputs.result }}
  setup-go:
    needs: prepare-matrix
    strategy:
      fail-fast: true
      matrix:
        os: ${{ fromJson(needs.prepare-matrix.outputs.matrix-arrays).os }}
        go-version: ${{ fromJson(needs.prepare-matrix.outputs.matrix-arrays).go-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version