name: Matrix Workflow
on: [push]

jobs:
  setup-go:
    continue-on-error: ${{ matrix.experimental == true }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        go-version: ['1.20', '1.21', '1.22']
        include:
          - os: ubuntu-latest
            is-ubuntu: true
          - os: macos-latest
            go-version: '1.21'
          - experimental: false 
          - os: ubuntu-latest
            go-version: '1.22'
            experimental: true
          - os: ubuntu-latest
            go-version: '1.23'
        exclude:
          - os: ubuntu-latest
            go-version: '1.20'
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.experimental == true
        run: exit 1
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version