name: Variables and Secrets
on: [push]

jobs:
  decrypt-file:
    runs-on: ubuntu-latest
    env:
      SECRET_DIR: "${{ github.env.HOME }}/secret"
    steps:
      - uses: actions/checkout@v4
      - name: Make Directory
        run: mkdir $SECRET_DIR
      - name: Decrypt File
        run: gpg --quiet --batch --yes --decrypt --passphrase=${{ secrets.PASSPHRASE }} --output $SECRET_DIR/secret.json
      - name: Print secret
        run: cat $SECRET_DIR/secret.json
  log-vars:
    runs-on: ubuntu-latest
    environment: 'production'
    env: 
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
    steps:
      - name: Run only if BOOLEAN_SECRET is true
        if: env.BOOLEAN_SECRET == 'false'
        run: echo "I ran"
      - name: Print Variables
        run: |
          echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
          echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"

