name: Variables and Secrets
on: [push]

jobs:
  log-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variables
        run: |
          echo "ENV_LEVEL_VAR: $REPO_LEVEL_VAR"
          echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"

