name: Workflow Commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon"
      - name: Setting an error message with parameters
        run: echo "::error title=Error title,file=main.go,line=8,endLine=9,col=5,endColumn=7::Missing Semicolon"
      - name: Setting an debug message with parameters
        run: echo "::debug title=Debug title,file=main.go,line=8,endLine=9,col=5,endColumn=7::Missing Semicolon"
      - name: Setting an warning message with parameters
        run: echo "::error title=Warning title,file=main.go,line=8,endLine=9,col=5,endColumn=7::Missing Semicolon"
      - name: Setting an notice message with parameters
        run: echo "::error title=Notice title,file=main.go,line=8,endLine=9,col=5,endColumn=7::Missing Semicolon"